### ISSUE TITLE
Can't start single player game, always shows "Connection refused"

### ISSUE THREAD

**Issue by amuhaimin02** [shlusiak/Freebloks-Android#6]
I don't understand. Do I need to be in the Wifi network in order to be able play it? I want to play the single player game, but the popup "Connection refused" keeps coming out. 

I'm on Android 4.4.2

**Comment by shlusiak** [comment]
Hi,

the single player game will open a server and connect to localhost. The connection refused comes from not being able to start the server part of the game before connecting locally but it's unclear to me what could cause this. Does this also happen after a fresh boot of the phone or after terminating the application (swiping it in the recent tasks list)? You do not need to be connected to a network for this to work but the game needs full network access to be able to connect locally.

Sascha

**Comment by Akmal02** [comment]
Well, it works fine in my friend's Android 5.1.1 though.
I can only play when I connect both me and my friend's phone via portable hotspot. Looks like it needs to be in Wifi network to be able to play it.
And when I turn off Wifi, the "Connection refused" pops out when I wamt to start a game, it. Reboot and clearing tasks doesn't seem to help
Maybe this is because I'm on 4.2.2 custom ROM that might screw things off.
But in my opinion, I think the multiplayer functionality should not be implemented in single player mode. I can even get past the dialog unless I am in the Wifi network

Hope you can look in into it...

**Comment by refola** [comment]
@shlusiak, mind reopening this issue?

I just installed the app and I'm getting the same error. My phone's on Android 9 (Pie), (specifically LineageOS 16, but it's really minimal in terms of departures from upstream Android). This is with version 1.3.0 of Freebloks, installed from F-Droid.

**Comment by shlusiak** [comment]
@refola thanks for reporting this. I have noticed this occasionally, and usually these are weird situations where a game is still running in the background that hasn't fully terminated at the time a new game is started. These are very rare though and in 99% of the cases this works for me, including the F-Droid build 1.3.0. 

When starting a new game, a listening TCP socket on port `59995` is bound to `*` (null) and the game then connects to the port on `ANY` (null). There is a possibility that the connection is either attempted before the socket is fully listening, or that the listening on that port fails, because there is already a socket open for the same source port. In both cases you would see a connection refused error, but both cases would be rare. I will think about randomising this port and ensuring again that the `connect` cannot happen before the `listen`.

If you cannot start a new game at all and always get the same error, even after force quitting and restarting the app, is it possible that there is anything interfering with the app trying to connect to localhost? Like a VPN or a firewall?

**Comment by refola** [comment]
I'm not using any VPNs or firewalls beyond whatever's built in to Android itself. I tried double-checking all permissions and force-closing all apps. That didn't work. But subsequently rebooting my phone *did* work.

I think it *might* be an app conflict where another app got the post first and the system didn't release it even after force-closing the app, but this is ignorant speculation as I don't know about Android networking internals. It's definitely not a matter of the system blocking it, otherwise it wouldn't work after rebooting.

> I will think about randomising this port

That sounds like a good fix. Or just keep incrementing the port number (with wraparound to the start of the ephemeral port range after the max) until it works.

By the way, is there a way to get a better error message? I imagine the Android runtime may have thrown an informative exception when attempting to claim an unavailable port.

**Comment by shlusiak** [comment]
I hope the latest update resolves this. I've replaced the connection to "127.0.0.1" with a local unix domain socket for local games.
